services:
  # Primary PostgreSQL database (production-like)
  postgres-primary:
    image: postgres:15-alpine
    container_name: querybird-postgres-primary
    environment:
      POSTGRES_DB: querybird_prod
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin_password_123
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8 --lc-collate=C --lc-ctype=C'
    ports:
      - '5432:5432'
    volumes:
      - postgres_primary_data:/var/lib/postgresql/data
      - ./init-scripts/init-primary.sql:/docker-entrypoint-initdb.d/01-init-primary.sql
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U admin -d querybird_prod']
      interval: 10s
      timeout: 5s
      retries: 5

  # Secondary PostgreSQL database (staging-like)
  postgres-staging:
    image: postgres:15-alpine
    container_name: querybird-postgres-staging
    environment:
      POSTGRES_DB: querybird_staging
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin_password_123
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8 --lc-collate=C --lc-ctype=C'
    ports:
      - '5433:5432'
    volumes:
      - postgres_staging_data:/var/lib/postgresql/data
      - ./init-scripts/init-staging.sql:/docker-entrypoint-initdb.d/01-init-staging.sql
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U admin -d querybird_staging']
      interval: 10s
      timeout: 5s
      retries: 5

  # MySQL database for testing
  mysql-test:
    image: mysql:8.0
    container_name: querybird-mysql-test
    environment:
      MYSQL_ROOT_PASSWORD: root_password_123
      MYSQL_DATABASE: querybird_mysql
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin_password_123
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init-scripts/init-mysql.sql:/docker-entrypoint-initdb.d/01-init-mysql.sql
    command: --authentication-policy=mysql_native_password --tls-version='' --require_secure_transport=OFF --mysqlx=OFF --pid-file=/var/run/mysqld/mysqld.pid --host-cache-size=0
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'admin', '-padmin_password_123']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_primary_data:
  postgres_staging_data:
  mysql_data:
  pgadmin_data:
