id: ete
name: erer
description: Export user data from PostgreSQL
input:
  postgres:
    name: er
    connection_info: "!secrets ete.database.er"
    sql:
      - name: users
        sql: |-
          SELECT 
                      rolname AS username,
                      rolsuper AS is_superuser,
                      rolcreaterole AS can_create_role,
                      rolcreatedb AS can_create_db,
                      rolcanlogin AS can_login,
                      CURRENT_TIMESTAMP AS last_login_time,
                      CURRENT_TIMESTAMP AS last_password_changed_time
                    FROM pg_roles
                    WHERE rolcanlogin = true;
transform: |-
  er.users.{
      "Project": "erer",
      "Entity Name": username & "::" & er.connection_info.db_name & "::" & er.connection_info.region,
      "Entity Type": "identity",
      "Entity Source Type": "user", 
      "Entity Source ID": username & "::" & er.connection_info.db_name & "::" & er.connection_info.region,
      "Entity Username": username,
      "Entity Email": username,
      "Entity - Has Access To Name": (is_superuser ? "Admin" : "User") & "::" & %.connection_info.db_name & "::" & %.connection_info.region,
      "Entity - Has Access To Source ID": (is_superuser ? "admin-role-001" : "user-role-001") & "::" & %.connection_info.db_name & "::" & %.connection_info.region,
      "Entity - Has Access To Entity Type": "connection",
      "Entity - Has Access To Source Type": "role",
      "Entity - Has Access To Permission Name": is_superuser ? "admin" : "member",
      "Entity - Has Access To Permission Value": "true",
      "Entity Status": can_login ? "active" : "inactive",
      "Entity First Name": $substringBefore(username, "."),
      "Entity Last Name": $substringAfter(username, "."),
      "Entity LastLoginTime": last_login_time,
      "Entity LastPasswordChangedTime": last_password_changed_time,
      "Entity MfaEnabled": "false"
    }
schedule: "* * * * *"
enabled: true
outputs: []
timeout: 30000
