id: example-connection-info
name: Example Connection Info Usage
description: Demonstrates how to use connection_info context in jsonata transforms
input:
  postgres:
    - name: production
      connection_info: '!secrets example.database.production'
      sql:
        - name: users
          sql: |-
            SELECT 
              'john.doe' AS username,
              true AS is_active,
              'admin' AS role
            FROM (VALUES (1)) AS t(dummy)
            LIMIT 1;
    - name: staging
      connection_info: '!secrets example.database.staging'
      sql:
        - name: users
          sql: |-
            SELECT 
              'jane.smith' AS username,
              false AS is_active,
              'user' AS role
            FROM (VALUES (1)) AS t(dummy)
            LIMIT 1;
transform: |-
  $merge([
    production.users.{
      "Environment": "Production",
      "Database": production.connection_info.db_name,
      "Region": production.connection_info.region,
      "Host": production.connection_info.host,
      "Username": username,
      "Status": is_active ? "Active" : "Inactive",
      "Role": role,
      "Connection Details": production.connection_info
    },
    staging.users.{
      "Environment": "Staging",
      "Database": staging.connection_info.db_name,
      "Region": staging.connection_info.region,
      "Host": staging.connection_info.host,
      "Username": username,
      "Status": is_active ? "Active" : "Inactive",
      "Role": role,
      "Connection Details": staging.connection_info
    }
  ])
schedule: 0 0 * * *
enabled: false
outputs:
  - type: file
    path: ./outputs/connection-info-example.json
    format: json
timeout: 30000
