id: sync-users
name: sync users
description: Export user data from PostgreSQL
input:
  postgres:
    - name: test1
      connection_info: '!secrets sync-users.database.test1'
      sql:
        - name: users
          sql: |-
            SELECT 
                        rolname AS username,
                        rolsuper AS is_superuser,
                        rolcreaterole AS can_create_role,
                        rolcreatedb AS can_create_db,
                        rolcanlogin AS can_login,
                        CURRENT_TIMESTAMP AS last_login_time,
                        CURRENT_TIMESTAMP AS last_password_changed_time
                      FROM pg_roles
                      WHERE rolcanlogin = true;
    - name: wsrwr
      connection_info: '!secrets sync-users.database.wsrwr'
      sql:
        - name: users
          sql: |-
            SELECT 
                        rolname AS username,
                        rolsuper AS is_superuser,
                        rolcreaterole AS can_create_role,
                        rolcreatedb AS can_create_db,
                        rolcanlogin AS can_login,
                        CURRENT_TIMESTAMP AS last_login_time,
                        CURRENT_TIMESTAMP AS last_password_changed_time
                      FROM pg_roles
                      WHERE rolcanlogin = true;
transform: |-
  $merge([
    test1.users.{
      "Project": "sync users",
      "Entity Name": username & "::" & test1.connection_info.db_name & "::" & test1.connection_info.region,
      "Entity Type": "identity",
      "Entity Source Type": "user",
      "Entity Source ID": username & "::" & test1.connection_info.db_name & "::" & test1.connection_info.region,
      "Entity Username": username,
      "Entity Email": username,
      "Entity - Has Access To Name": is_superuser ? "Admin" : "User",
      "Entity - Has Access To Source ID": is_superuser ? "admin-role-001" : "user-role-001",
      "Entity - Has Access To Entity Type": "connection",
      "Entity - Has Access To Source Type": "role",
      "Entity - Has Access To Permission Name": is_superuser ? "admin" : "member",
      "Entity - Has Access To Permission Value": "true",
      "Entity Status": can_login ? "active" : "inactive",
      "Entity First Name": $substringBefore(username, "."),
      "Entity Last Name": $substringAfter(username, "."),
      "Entity LastLoginTime": last_login_time,
      "Entity LastPasswordChangedTime": last_password_changed_time,
      "Entity MfaEnabled": "false"
    },
    wsrwr.users.{
      "Project": "sync users",
      "Entity Name": username & "::" & wsrwr.connection_info.db_name & "::" & wsrwr.connection_info.region,
      "Entity Type": "identity",
      "Entity Source Type": "user",
      "Entity Source ID": username & "::" & wsrwr.connection_info.db_name & "::" & wsrwr.connection_info.region,
      "Entity Username": username,
      "Entity Email": username,
      "Entity - Has Access To Name": is_superuser ? "Admin" : "User",
      "Entity - Has Access To Source ID": is_superuser ? "admin-role-001" : "user-role-001",
      "Entity - Has Access To Entity Type": "connection",
      "Entity - Has Access To Source Type": "role",
      "Entity - Has Access To Permission Name": is_superuser ? "admin" : "member",
      "Entity - Has Access To Permission Value": "true",
      "Entity Status": can_login ? "active" : "inactive",
      "Entity First Name": $substringBefore(username, "."),
      "Entity Last Name": $substringAfter(username, "."),
      "Entity LastLoginTime": last_login_time,
      "Entity LastPasswordChangedTime": last_password_changed_time,
      "Entity MfaEnabled": "false"
    }
  ])
schedule: 0 2 * * *
enabled: true
outputs:
  - type: http
    endpoint: https://app.balkan.id/api/rest/v0/entitlements/upload-url
    method: POST
    headers:
      X-Api-Key-ID: '!secrets sync-users-postgress.api_keys.balkan_key_id'
      X-Api-Key-Secret: '!secrets sync-users-postgress.api_keys.balkan_key_secret'
    body:
      integrationId: '!secrets sync-users-postgress.api_keys.balkan_integration_id'
    response_url_field: url
    upload_method: PUT
    format: csv
    retryCount: 3
timeout: 30000
