# DEPRECATED: Native Binary Releases
# 
# This workflow has been replaced with Docker-only releases.
# See: docker-release.yml for the new Docker release process.
# 
# QueryBird now uses GitHub Container Registry for distribution:
# - ghcr.io/trutohq/querybird:latest
# - ghcr.io/trutohq/querybird:v1.0.0
#
# Native binary releases are no longer supported.
# Use Docker deployment for all environments.

name: Deprecated - Native Binary Release

on:
  # Disabled - no triggers
  workflow_dispatch:
    inputs:
      deprecated:
        description: 'This workflow is deprecated. Use docker-release.yml instead.'
        required: false

jobs:
  deprecated-notice:
    runs-on: ubuntu-latest
    steps:
      - name: Deprecation Notice
        run: |
          echo "⚠️  DEPRECATED WORKFLOW"
          echo ""
          echo "This workflow for native binary releases is deprecated."
          echo "QueryBird now uses Docker-only deployment."
          echo ""
          echo "🐳 New Docker Release Process:"
          echo "  - Images: ghcr.io/trutohq/querybird:latest"
          echo "  - Workflow: docker-release.yml"
          echo "  - Documentation: README.md#production-deployment"
          echo ""
          echo "Please use the Docker deployment approach."
          exit 1
