name: Release Binaries

on:
  release:
    types: [published]
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release'
        required: true
        default: '2.0.0'

permissions:
  contents: write

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Setup signing keys
        env:
          SIGNING_PRIVATE_KEY: ${{ secrets.SIGNING_PRIVATE_KEY }}
          SIGNING_PUBLIC_KEY: ${{ secrets.SIGNING_PUBLIC_KEY }}
        run: |
          mkdir -p keys
          if [ -n "$SIGNING_PRIVATE_KEY" ]; then
            echo "$SIGNING_PRIVATE_KEY" > keys/querybird-private.pem
            echo "$SIGNING_PUBLIC_KEY" > keys/querybird-public.pem
            chmod 600 keys/querybird-private.pem
            echo "Using provided signing keys"
          else
            echo "No signing keys provided, generating new ones"
            bun run scripts/sign-binaries.ts generate-keys
          fi

      - name: Build binaries for all platforms
        env:
          VERSION: ${{ github.event.release.tag_name || github.ref_name || github.event.inputs.version }}
        run: |
          echo "Building for version: $VERSION"
          echo "Event name: ${{ github.event_name }}"
          echo "Ref: ${{ github.ref }}"
          echo "Ref name: ${{ github.ref_name }}"

          # Set version in package.json
          sed -i "s/\"version\": \".*\"/\"version\": \"$VERSION\"/" package.json

          # Build all binaries
          bun run build:binaries

          # List what was built
          echo "Built files:"
          ls -la dist/binaries/

      - name: Sign binaries
        run: |
          bun run scripts/sign-binaries.ts sign-all

      - name: Create distribution archives
        env:
          VERSION: ${{ github.event.release.tag_name || github.ref_name || github.event.inputs.version }}
        run: |
          bun run scripts/create-distribution.ts

      - name: Create or update release
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.release.tag_name }}
          name: ${{ github.event.release.name }}
          body: ${{ github.event.release.body }}
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            dist/releases/*.zip
            dist/releases/querybird-v*-checksums.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create release from tag
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          body: |
            ## QueryBird ${{ github.ref_name }}

            This release was automatically created from tag ${{ github.ref_name }}.

            ### What's Included
            - Cross-platform binaries for Linux, macOS, and Windows
            - Installation scripts for all platforms
            - Setup utilities for PostgreSQL
            - SHA256 checksums for verification

            ### Downloads
            Choose the appropriate binary for your platform and follow the installation instructions.
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            dist/releases/*.zip
            dist/releases/querybird-v*-checksums.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload artifacts
        if: github.event_name == 'workflow_dispatch'
        uses: actions/upload-artifact@v4
        with:
          name: querybird-release-v${{ github.event.inputs.version }}
          path: |
            dist/releases/
